[project]
name = "qdqa-0-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "accelerate==0.30.0",
    "evaluate==0.4.6",
    "faiss-gpu>=1.7.2",
    "pandas==2.3.3",
    "transformers==4.39.3",
]
